services:
  bff-upstream:
    build:
      context: ./bff-upstream
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOWNSTREAM_GRAPHQL_URL: http://bff-downstream:8080/graphql
    depends_on:
      - redis
  bff-downstream:
    build:
      context: ./bff-downstream
    ports:
      - "8080:8080"
    environment:
      UPSTREAM_GRAPHQL_URL: http://bff-upstream:8081/graphql
    depends_on:
      - bff-upstream
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
